@WebHook.DeliveryService_HostAddress = https://localhost:7143

POST {{WebHook.DeliveryService_HostAddress}}/api/webhook/v1/webhooks/
Content-Type: application/json

{
  "Url": "https://localhost:7392/webhook"
}

###

POST {{WebHook.DeliveryService_HostAddress}}/api/webhook/v1/deliveries/
Content-Type: application/json

{
  "Id": "00000000-0000-0000-0000-000000000000",
  "Sender": "Sender Name",
  "Receiver": "Receiver Name",
  "SenderAddress": "Sender Address",
  "ReceiverAddress": "Receiver Address",
  "PackageInfo": "Package Info"
}

###
