global using CQRS.Library.BorrowingApi.Infrastructure.Data;
global using CQRS.Library.BorrowingApi.Infrastructure.Entity;
global using EventBus.Events;
global using EventBus.Kafka;
global using Microsoft.EntityFrameworkCore;
global using CQRS.Library.BorrowingApi.IntegrationEvents;
global using CQRS.Library.BorrowingApi.Apis;
global using CQRS.Library.BorrowingApi.Bootstraping;
global using Microsoft.AspNetCore.Http.HttpResults;