@CQRS.Library.BorrowingHistoryApi_HostAddress = https://localhost:7204

GET {{CQRS.Library.BorrowingHistoryApi_HostAddress}}/api/cqrs/v1/history/items/
Accept: application/json

{
  "pageSize": 10,
  "pageIndex": 1,
}

###
