using ModelContextProtocol.Server;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Mcp.CQRS.Library.McpServer;

[McpServerToolType]
public class LibraryTool
{
    [McpServerTool]
    public static async Task<string> GetBooks(ILibraryService libraryService, CancellationToken cancellationToken)
    {
        var books = await libraryService.GetBooks(cancellationToken);

        return JsonSerializer.Serialize(books);
    }

    [McpServerTool]
    public static async Task<string> GetBookDetails(ILibraryService libraryService, string bookId, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(bookId, out var parsedBookId))
        {
            throw new ArgumentException($"Invalid book ID format: '{bookId}'. Expected a valid GUID.", nameof(bookId));
        }

        var book = await libraryService.GetBookById(parsedBookId, cancellationToken) ?? throw new KeyNotFoundException($"Book with ID '{bookId}' not found.");
        return JsonSerializer.Serialize(book);
    }

    [McpServerTool]
    public static async Task<string> GetBorrowers(ILibraryService libraryService, CancellationToken cancellationToken)
    {
        var borrowers = await libraryService.GetBorrowers(cancellationToken);
        return JsonSerializer.Serialize(borrowers);
    }

    [McpServerTool]
    public static async Task<string> GetBorrowerDetails(ILibraryService libraryService, string borrowerId, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(borrowerId, out var parsedBorrowerId))
        {
            throw new ArgumentException($"Invalid borrower ID format: '{borrowerId}'. Expected a valid GUID.", nameof(borrowerId));
        }
        var borrower = await libraryService.GetBorrowerById(parsedBorrowerId, cancellationToken) ?? throw new KeyNotFoundException($"Borrower with ID '{borrowerId}' not found.");
        return JsonSerializer.Serialize(borrower);
    }

    [McpServerTool]
    public static async Task<string> GetBorrowings(ILibraryService libraryService, CancellationToken cancellationToken)
    {
        var borrowings = await libraryService.GetBorrowings(cancellationToken);
        return JsonSerializer.Serialize(borrowings);
    }

    [McpServerTool]
    public static async Task<string> GetBorrowingDetails(ILibraryService libraryService, string borrowingId, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(borrowingId, out var parsedBorrowingId))
        {
            throw new ArgumentException($"Invalid borrowing ID format: '{borrowingId}'. Expected a valid GUID.", nameof(borrowingId));
        }
        var borrowing = await libraryService.GetBorrowingById(parsedBorrowingId, cancellationToken) ?? throw new KeyNotFoundException($"Borrowing with ID '{borrowingId}' not found.");
        return JsonSerializer.Serialize(borrowing);
    }

    [McpServerTool]
    public static async Task<string> GetBorrowingHistoryItems(ILibraryService libraryService, Guid? borrowerId, Guid? bookId, string query, CancellationToken cancellationToken)
    {
        var borrowingHistoryItems = await libraryService.GetBorrowingHistoryItems(borrowerId, bookId, query, cancellationToken);
        return JsonSerializer.Serialize(borrowingHistoryItems);
    }

    [McpServerTool]
    public static async Task<string> CreateBook(ILibraryService libraryService, string title, string author, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(title))
        {
            throw new ArgumentException("Title is required.", nameof(title));
        }

        if (string.IsNullOrWhiteSpace(author))
        {
            throw new ArgumentException("Author is required.", nameof(author));
        }

        var book = new Book
        {
            Id = Guid.Empty, // Will be generated by the service
            Title = title,
            Author = author
        };

        var createdBook = await libraryService.CreateBook(book, cancellationToken);
        return JsonSerializer.Serialize(createdBook);
    }

    [McpServerTool]
    public static async Task<string> UpdateBook(ILibraryService libraryService, string bookId, string title, string author, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(bookId, out var parsedBookId))
        {
            throw new ArgumentException($"Invalid book ID format: '{bookId}'. Expected a valid GUID.", nameof(bookId));
        }

        if (string.IsNullOrWhiteSpace(title))
        {
            throw new ArgumentException("Title is required.", nameof(title));
        }

        if (string.IsNullOrWhiteSpace(author))
        {
            throw new ArgumentException("Author is required.", nameof(author));
        }

        var book = new Book
        {
            Id = parsedBookId,
            Title = title,
            Author = author
        };

        await libraryService.UpdateBook(parsedBookId, book, cancellationToken);
        return JsonSerializer.Serialize(new { message = "Book updated successfully", bookId = parsedBookId });
    }

    [McpServerTool]
    public static async Task<string> CreateBorrower(ILibraryService libraryService, string name, string address, string phoneNumber, string email, CancellationToken cancellationToken)
    {
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Name is required.", nameof(name));
        }

        if (string.IsNullOrWhiteSpace(address))
        {
            throw new ArgumentException("Address is required.", nameof(address));
        }

        if (string.IsNullOrWhiteSpace(phoneNumber))
        {
            throw new ArgumentException("Phone number is required.", nameof(phoneNumber));
        }

        if (string.IsNullOrWhiteSpace(email))
        {
            throw new ArgumentException("Email is required.", nameof(email));
        }

        var borrower = new Borrower
        {
            Id = Guid.Empty, // Will be generated by the service
            Name = name,
            Address = address,
            PhoneNumber = phoneNumber,
            Email = email
        };

        var createdBorrower = await libraryService.CreateBorrower(borrower, cancellationToken);
        return JsonSerializer.Serialize(createdBorrower);
    }

    [McpServerTool]
    public static async Task<string> UpdateBorrower(ILibraryService libraryService, string borrowerId, string name, string address, string phoneNumber, string email, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(borrowerId, out var parsedBorrowerId))
        {
            throw new ArgumentException($"Invalid borrower ID format: '{borrowerId}'. Expected a valid GUID.", nameof(borrowerId));
        }

        if (string.IsNullOrWhiteSpace(name))
        {
            throw new ArgumentException("Name is required.", nameof(name));
        }

        if (string.IsNullOrWhiteSpace(address))
        {
            throw new ArgumentException("Address is required.", nameof(address));
        }

        if (string.IsNullOrWhiteSpace(phoneNumber))
        {
            throw new ArgumentException("Phone number is required.", nameof(phoneNumber));
        }

        if (string.IsNullOrWhiteSpace(email))
        {
            throw new ArgumentException("Email is required.", nameof(email));
        }

        var borrower = new Borrower
        {
            Id = parsedBorrowerId,
            Name = name,
            Address = address,
            PhoneNumber = phoneNumber,
            Email = email
        };

        await libraryService.UpdateBorrower(parsedBorrowerId, borrower, cancellationToken);
        return JsonSerializer.Serialize(new { message = "Borrower updated successfully", borrowerId = parsedBorrowerId });
    }

    [McpServerTool]
    public static async Task<string> BorrowBook(ILibraryService libraryService, string borrowerId, string bookId, string validUntil, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(borrowerId, out var parsedBorrowerId))
        {
            throw new ArgumentException($"Invalid borrower ID format: '{borrowerId}'. Expected a valid GUID.", nameof(borrowerId));
        }

        if (!Guid.TryParse(bookId, out var parsedBookId))
        {
            throw new ArgumentException($"Invalid book ID format: '{bookId}'. Expected a valid GUID.", nameof(bookId));
        }

        if (!DateTime.TryParse(validUntil, out var parsedValidUntil))
        {
            throw new ArgumentException($"Invalid date format: '{validUntil}'. Expected a valid date.", nameof(validUntil));
        }

        var borrowing = new Borrowing
        {
            Id = Guid.Empty, // Will be generated by the service
            BorrowerId = parsedBorrowerId,
            BookId = parsedBookId,
            ValidUntil = parsedValidUntil
        };

        var createdBorrowing = await libraryService.CreateBorrowing(borrowing, cancellationToken);
        return JsonSerializer.Serialize(createdBorrowing);
    }

    [McpServerTool]
    public static async Task<string> ReturnBook(ILibraryService libraryService, string borrowingId, CancellationToken cancellationToken)
    {
        if (!Guid.TryParse(borrowingId, out var parsedBorrowingId))
        {
            throw new ArgumentException($"Invalid borrowing ID format: '{borrowingId}'. Expected a valid GUID.", nameof(borrowingId));
        }

        await libraryService.ReturnBook(parsedBorrowingId, cancellationToken);
        return JsonSerializer.Serialize(new { message = "Book returned successfully", borrowingId = parsedBorrowingId });
    }

}
