@BFF.ProductCatalog.SearchService_HostAddress = https://localhost:7118

GET {{BFF.ProductCatalog.SearchService_HostAddress}}/api/bff/v1/products/search?query=sample&offset=0&limit=10
Accept: application/json

###
