@CQRS.Library.BorrowingApi_HostAddress = https://localhost:7070

GET {{CQRS.Library.BorrowingApi_HostAddress}}/api/cqrs/v1/borrowings
Accept: application/json

###

POST {{CQRS.Library.BorrowingApi_HostAddress}}/api/cqrs/v1/borrowings HTTP/1.1
Content-Type: application/json

{
  "Id": "00000000-0000-0000-0000-000000000000",
  "BorrowerId": "019557EB-49D7-7007-BEDE-5F22B35963D0",
  "BookId": "019557EE-978C-7CE8-9152-73637B6DC9F5",
  "ValidUntil": "2025-09-01T00:00:00Z"
}