@CQRS.Library.BookApi_HostAddress = https://localhost:7141
@CQRS.Library.BookApi_GatewayAddress = http://localhost:9999

GET {{CQRS.Library.BookApi_HostAddress}}/api/cqrs/v1/books
Accept: application/json

###

POST {{CQRS.Library.BookApi_HostAddress}}/api/cqrs/v1/books HTTP/1.1
Content-Type: application/json

{
  "Id": "019557EE-978C-7CE8-9152-73637B6DC9F5",
  "Title": "The Fellowship of the Ring",
  "Author": "J. R. R. Tolkien"
}

###

POST {{CQRS.Library.BookApi_HostAddress}}/api/cqrs/v1/books HTTP/1.1
Content-Type: application/json

{
  "Id": "00000000-0000-0000-0000-000000000000",
  "Title": "Harry Potter and the Philosopher's Stone",
  "Author": "J. K. Rowling"
}

###
POST {{CQRS.Library.BookApi_GatewayAddress}}/api/cqrs/v1/books HTTP/1.1
Content-Type: application/json

{
  "Id": "00000000-0000-0000-0000-000000000000",
  "Title": "Harry Potter and the Philosopher's Stone",
  "Author": "J. K. Rowling"
}